services:
  myapp:
    build: .
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    command: /bin/bash
    shm_size: '2gb'  # Increase from 1gb to 2gb or whatever size you need
    deploy:
      resources:
          reservations:
              devices:
                  - driver: nvidia
                    device_ids: ['0', '1', '2', '3']
                    capabilities: [ gpu ]